# Generated by Django 4.1.5 on 2023-04-21 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobadmin', '0006_alter_freelanceregistration_contact_and_more'),
        ('provider', '0004_remove_vacancy_resume'),
        ('seeker', '0003_addfeedback_seeker_id_addfeedback_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobadmin.seekerregistration')),
                ('vacancy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.vacancy')),
            ],
        ),
    ]
