# Generated by Django 4.1.5 on 2023-03-10 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobadmin', '0003_alter_login_keyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=25)),
                ('keyuser', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=30)),
                ('experience', models.IntegerField(max_length=10)),
                ('vacancies', models.IntegerField()),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobadmin.providerregistration')),
            ],
        ),
    ]
