# Generated by Django 4.1.5 on 2023-03-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
