# Generated by Django 4.1.5 on 2023-04-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_vacancy_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='resume',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
