# Generated by Django 4.1.5 on 2023-04-21 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_vacancy_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='resume',
        ),
    ]
