# Generated by Django 4.1.5 on 2023-04-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_remove_vacancy_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='company_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
