# Generated by Django 4.1.5 on 2023-02-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobadmin', '0002_freelanceregistration_providerregistration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='keyuser',
            field=models.CharField(max_length=30),
        ),
    ]
