# Generated by Django 4.1.5 on 2023-03-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobadmin', '0003_alter_login_keyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerregistration',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
