# Generated by Django 4.1.5 on 2023-03-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobadmin', '0004_providerregistration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceregistration',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
