# Generated by Django 4.1.5 on 2023-03-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobadmin', '0005_freelanceregistration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelanceregistration',
            name='contact',
            field=models.BigIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='providerregistration',
            name='contact',
            field=models.BigIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='seekerregistration',
            name='contact',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
